# Generated by Django 5.1.6 on 2025-02-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maker', models.CharField(verbose_name=30)),
                ('model', models.CharField(verbose_name=30)),
                ('year', models.PositiveIntegerField()),
                ('color', models.CharField(verbose_name=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=30)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='phone_images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
